### PR TITLE
Add support for client side camelCased keys

### PR DESCRIPTION
**Pull request by yusinto**
Hi guys, we are almost going live with launch darkly and so far we are loving it! One thing I found while dealing with keys is that the dash-separated keys (also called kebab-cased) don't play nice with json and javascript in general. For example, I can't do :

`
const flag = featureFlags.show-red-button; // does not work
`

Instead, I have to do:

`
const flag = featureFlags['show-red-button']; // works, but not very developer friendly
`

So I spent some time adding code to the js client to support camelCased keys so front end devs like me can access the feature flags using camel cased keys:

`
const flag = featureFlags.showRedButton; // this works now
`

The way I do it is by lowercasing and stripping dashes off keys in the sdk prior to accessing it in the flags object. I have added comprehensive unit tests to ensure existing kebab-cased keys still work and also ensuring the new camelCasedKeys work. 

At the moment we are manually doing this in our application, adding quite a bit of boilerplate code in process to camel case keys manually when accessing and then storing the flags. It will be good to have this in the sdk so we can remove all that boilerplate code and focus on the good stuff!

Please review and let me know if this is ok.

Thanks,
Yus

### CODE REVIEW

**Comment by apucacao** [comment]
Thanks @yusinto ! We'll review this shortly.

**Comment by yusinto** [comment]
Thanks Alex!

**Comment by yusinto** [comment]
@apucacao @jkodumal I'm withdrawing this pull request because I'm planning to release a package that will encapsulate the camel case logic that I wrote here. That way it's less intrusive to your code, and the package can be decoupled and maintained separately as needed.

**Comment by jkodumal** [comment]
Thanks @yusinto -- sorry for the long delay on getting feedback to you on this one.

**Comment by yusinto** [comment]
Not a problem, in fact it's actually a blessing in disguise, gave me more
time to devise a better solution.

We are live with feature flags btw! Really working well for us so far.

Thanks John

**Pull request closed without merging**
